/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CrediVaultInterface extends Interface {
    getFunction(nameOrSignature: "contractBalance" | "createCase" | "executePayout" | "getCase" | "getRecipients" | "isExecutor" | "owner" | "payInvoice" | "setAllocation" | "setExecutor"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllocationUpdated" | "CaseCreated" | "Deposit" | "Executed" | "ExecutorUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'contractBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'createCase', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'executePayout', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCase', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRecipients', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isExecutor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'payInvoice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setAllocation', values: [BytesLike, AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'setExecutor', values: [AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'contractBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executePayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecipients', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExecutor', data: BytesLike): Result;
  }

  
    export namespace AllocationUpdatedEvent {
      export type InputTuple = [caseId: BytesLike];
      export type OutputTuple = [caseId: string];
      export interface OutputObject {caseId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CaseCreatedEvent {
      export type InputTuple = [caseId: BytesLike, debtor: AddressLike, amountDue: BigNumberish];
      export type OutputTuple = [caseId: string, debtor: string, amountDue: bigint];
      export interface OutputObject {caseId: string, debtor: string, amountDue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositEvent {
      export type InputTuple = [caseId: BytesLike, from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [caseId: string, from: string, amount: bigint];
      export interface OutputObject {caseId: string, from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutedEvent {
      export type InputTuple = [caseId: BytesLike, totalPaid: BigNumberish];
      export type OutputTuple = [caseId: string, totalPaid: bigint];
      export interface OutputObject {caseId: string, totalPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutorUpdatedEvent {
      export type InputTuple = [executor: AddressLike, allowed: boolean];
      export type OutputTuple = [executor: string, allowed: boolean];
      export interface OutputObject {executor: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CrediVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): CrediVault;
    waitForDeployment(): Promise<this>;

    interface: CrediVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    contractBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createCase: TypedContractMethod<
      [caseId: BytesLike, debtor: AddressLike, amountDue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executePayout: TypedContractMethod<
      [caseId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getCase: TypedContractMethod<
      [caseId: BytesLike, ],
      [[string, bigint, bigint, boolean, boolean] & {debtor: string, due: bigint, paid: bigint, configured: boolean, executed: boolean }],
      'view'
    >
    

    
    getRecipients: TypedContractMethod<
      [caseId: BytesLike, ],
      [[string[], bigint[]]],
      'view'
    >
    

    
    isExecutor: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    payInvoice: TypedContractMethod<
      [caseId: BytesLike, ],
      [void],
      'payable'
    >
    

    
    setAllocation: TypedContractMethod<
      [caseId: BytesLike, recipients: AddressLike[], allocations: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    setExecutor: TypedContractMethod<
      [executor: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'contractBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCase'): TypedContractMethod<
      [caseId: BytesLike, debtor: AddressLike, amountDue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executePayout'): TypedContractMethod<
      [caseId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCase'): TypedContractMethod<
      [caseId: BytesLike, ],
      [[string, bigint, bigint, boolean, boolean] & {debtor: string, due: bigint, paid: bigint, configured: boolean, executed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getRecipients'): TypedContractMethod<
      [caseId: BytesLike, ],
      [[string[], bigint[]]],
      'view'
    >;
getFunction(nameOrSignature: 'isExecutor'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payInvoice'): TypedContractMethod<
      [caseId: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'setAllocation'): TypedContractMethod<
      [caseId: BytesLike, recipients: AddressLike[], allocations: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExecutor'): TypedContractMethod<
      [executor: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllocationUpdated'): TypedContractEvent<AllocationUpdatedEvent.InputTuple, AllocationUpdatedEvent.OutputTuple, AllocationUpdatedEvent.OutputObject>;
getEvent(key: 'CaseCreated'): TypedContractEvent<CaseCreatedEvent.InputTuple, CaseCreatedEvent.OutputTuple, CaseCreatedEvent.OutputObject>;
getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'Executed'): TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
getEvent(key: 'ExecutorUpdated'): TypedContractEvent<ExecutorUpdatedEvent.InputTuple, ExecutorUpdatedEvent.OutputTuple, ExecutorUpdatedEvent.OutputObject>;

    filters: {
      
      'AllocationUpdated(bytes32)': TypedContractEvent<AllocationUpdatedEvent.InputTuple, AllocationUpdatedEvent.OutputTuple, AllocationUpdatedEvent.OutputObject>;
      AllocationUpdated: TypedContractEvent<AllocationUpdatedEvent.InputTuple, AllocationUpdatedEvent.OutputTuple, AllocationUpdatedEvent.OutputObject>;
    

      'CaseCreated(bytes32,address,uint256)': TypedContractEvent<CaseCreatedEvent.InputTuple, CaseCreatedEvent.OutputTuple, CaseCreatedEvent.OutputObject>;
      CaseCreated: TypedContractEvent<CaseCreatedEvent.InputTuple, CaseCreatedEvent.OutputTuple, CaseCreatedEvent.OutputObject>;
    

      'Deposit(bytes32,address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'Executed(bytes32,uint256)': TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
      Executed: TypedContractEvent<ExecutedEvent.InputTuple, ExecutedEvent.OutputTuple, ExecutedEvent.OutputObject>;
    

      'ExecutorUpdated(address,bool)': TypedContractEvent<ExecutorUpdatedEvent.InputTuple, ExecutorUpdatedEvent.OutputTuple, ExecutorUpdatedEvent.OutputObject>;
      ExecutorUpdated: TypedContractEvent<ExecutorUpdatedEvent.InputTuple, ExecutorUpdatedEvent.OutputTuple, ExecutorUpdatedEvent.OutputObject>;
    
    };
  }